export let data = [
            {   
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (1).webp',
                author: 'Марсель Руссо',
                name: 'Охота Амура',
                type: 'Холст, масло (50х80)',
                price: '14 500'
            },
            {
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (2).webp',
                author: 'Анри Селин',
                name: 'Дама с собачкой',
                type: 'Акрил, бумага (50х80)',
                price: '16 500',
            },
            {
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (3).webp',
                author: 'Франсуа Дюпон',
                name: 'Процедура',
                type: 'Цветная литография (40х60)',
                price: '20 000',
            },
            {
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (4).webp',
                author: 'Луи Детуш',
                name: 'Роза',
                type: 'Бумага, акрил (50х80)',
                price: '12 000',
            },
            {
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (5).webp',
                author: 'Франсуа Дюпон',
                name: 'Птичья трапеза',
                type: 'Цветная литография (40х60)',
                price: '22 500',
            },
            {
                country: "France",
                countryRU: "Франция",
                img: './img/france/03 (6).webp',
                author: 'Пьер Моранж',
                name: 'Пейзаж с рыбой',
                type: 'Цветная литография (40х60)',
                price: '20 000',
            },

            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03-_7__1.webp',
                author: 'Курт Вернеро',
                name: 'Над городом',
                type: 'Цветная литография (40х60)',
                price: '16 000'
            },
            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03-_8__1.webp',
                author: 'Макс Рихтер',
                name: 'Птенцы',
                type: 'Холст, масло (50х80)',
                price: '14 500',
            },
            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03 (9).webp',
                author: 'Мартин Майер',
                name: 'Среди листьев',
                type: 'Цветная литография (40х60)',
                price: '20 000',
            },
            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03 (10).webp',
                author: 'Герман Беккер',
                name: 'Яркая птица',
                type: 'Цветная литография (40х60)',
                price: '13 000',
            },
            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03 (11).webp',
                author: 'Вульф Бауэр',
                name: 'Дятлы',
                type: 'Бумага, акрил (50х80)',
                price: '22 500',
            },
            {
                country: "Germany",
                countryRU: "Германия",
                img: './img/germany/03 (12).webp',
                author: 'Вальтер Хартманн',
                name: 'Большие воды',
                type: 'Бумага, акрил (50х80)',
                price: '23 000',
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (13).webp',
                author: 'Пол Смит',
                name: 'Дикий зверь',
                type: 'Акварель, бумага (50х80)',
                price: '19 500'
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (14).webp',
                author: 'Джон Уайт',
                name: 'Скалистый берег',
                type: 'Цветная литография (40х60)',
                price: '17 500'
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (15).webp',
                author: 'Джим Уотсон',
                name: 'Река и горы',
                type: 'Акварель, бумага (50х80) ',
                price: '20 500'
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (16).webp',
                author: 'Юджин Зиллион',
                name: 'Белый попугай',
                type: 'Цветная литография (40х60)',
                price: '15 500'
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (17).webp',
                author: 'Эрик Гиллман',
                name: 'Ночная рыба',
                type: 'Бумага, акрил (50х80)',
                price: '12 500'
            },
            {
                country: "England",
                countryRU: "Англия",
                img: './img/england/03 (18).webp',
                author: 'Альфред Барр',
                name: 'Рыжий кот',
                type: 'Цветная литография (40х60)',
                price: '22 000'
            },
]